name: Build and Publish NPM Package

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important for being able to push back to the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set this to the node version you want to use
        registry-url: 'https://registry.npmjs.org/'

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # todo: add automatic version bumping and push to repo
    # - name: Bump package version
    #  run: |
    #    git checkout main
    #    npm version patch
    #    git push
    
    #   env:
    #    GIT_COMMITTER_NAME: GitHub Actions
    #    GIT_COMMITTER_EMAIL: actions@github.com


    - name: Publish to NPM
      run: |
        npm install --legacy-peer-deps
        npm run build 
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


